data: data/crop_chula
weights: ''
img_size:
- 64
- 64
cfg: data/crop_rbc/param.yaml
workers: 4
epochs: 300
batch_size: 16
val_batch_size: 1
adam: false
evaluate: false
seed: 8888
gpu: '0'
amp: true
cache: null
save_dir: runs/crop_chula
